---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "lotus-cpr"
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "lotus-cpr"
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "lotus-cpr"
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        timestamp: "{{ date "20060102150405" .Release.Time }}"
    spec:
      containers:
      - name: main
        command: ["/lotus-cpr"]
        env:
        - name: LOTUS_CPR_LISTEN
          value: ":{{ .Values.listenPort }}"
        - name: LOTUS_CPR_STORE_PATH
          value: "/data"
        - name: LOTUS_CPR_BLOCKSTORE_BASEURL
          value: "{{ .Values.blockstoreBaseURL }}"
        - name: LOTUS_CPR_LOG_LEVEL
          value: "{{ .Values.logLevel }}"
        - name: LOTUS_CPR_HUMANIZE_LOGS
          value: "{{ .Values.humanizeLogs }}"
        - name: LOTUS_CPR_API
          value: "{{ .Values.lotusAPI }}"
        - name: LOTUS_CPR_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.lotusAPITokenSecret }}"
              key: jwt-ro-privs-token
        image: "{{ .Values.image }}"
        imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        ports:
        - containerPort: {{ .Values.listenPort }}
          name: api
          protocol: TCP
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: cache
          mountPath: /data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: cache
      labels:
        app.kubernetes.io/name: "lotus-cpr"
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.volume.size }}
      volumeMode: Filesystem
      storageClassName: {{ .Values.volume.storageClassName }}
